package co.edu.udea.usi.dto;
// Generated Apr 27, 2018 3:29:35 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MainFrame generated by hbm2java
 */
public class MainFrame implements java.io.Serializable {

	private String serialNumber;
	private String stockNumber;
	private String reference;
	private String brand;
	private String processor;
	private int ram;
	private String hardDrive;
	private String mainBoard;
	private Set users = new HashSet(0);

	public MainFrame() {
	}

	public MainFrame(String serialNumber, String stockNumber, String reference, String brand, String processor, int ram,
			String hardDrive, String mainBoard) {
		this.serialNumber = serialNumber;
		this.stockNumber = stockNumber;
		this.reference = reference;
		this.brand = brand;
		this.processor = processor;
		this.ram = ram;
		this.hardDrive = hardDrive;
		this.mainBoard = mainBoard;
	}

	public MainFrame(String serialNumber, String stockNumber, String reference, String brand, String processor, int ram,
			String hardDrive, String mainBoard, Set users) {
		this.serialNumber = serialNumber;
		this.stockNumber = stockNumber;
		this.reference = reference;
		this.brand = brand;
		this.processor = processor;
		this.ram = ram;
		this.hardDrive = hardDrive;
		this.mainBoard = mainBoard;
		this.users = users;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getStockNumber() {
		return this.stockNumber;
	}

	public void setStockNumber(String stockNumber) {
		this.stockNumber = stockNumber;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getProcessor() {
		return this.processor;
	}

	public void setProcessor(String processor) {
		this.processor = processor;
	}

	public int getRam() {
		return this.ram;
	}

	public void setRam(int ram) {
		this.ram = ram;
	}

	public String getHardDrive() {
		return this.hardDrive;
	}

	public void setHardDrive(String hardDrive) {
		this.hardDrive = hardDrive;
	}

	public String getMainBoard() {
		return this.mainBoard;
	}

	public void setMainBoard(String mainBoard) {
		this.mainBoard = mainBoard;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
