package co.edu.udea.usi.dto;
// Generated Apr 27, 2018 3:29:35 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request implements java.io.Serializable {

	private Integer idRequest;
	private TypeRequest typeRequest;
	private User user;
	private Date date;
	private String eventTime;
	private String office;
	private String description;
	private String channel;
	private Integer priority;
	private Integer level;
	private Character state;
	private Set maintenanceEvents = new HashSet(0);
	private Set transferEvents = new HashSet(0);
	private Set sharedEvents = new HashSet(0);
	private Set generalEvents = new HashSet(0);
	private Set modificationEvents = new HashSet(0);

	public Request() {
	}

	public Request(TypeRequest typeRequest, User user, Date date, String eventTime) {
		this.typeRequest = typeRequest;
		this.user = user;
		this.date = date;
		this.eventTime = eventTime;
	}

	public Request(TypeRequest typeRequest, User user, Date date, String eventTime, String office, String description,
			String channel, Integer priority, Integer level, Character state, Set maintenanceEvents, Set transferEvents,
			Set sharedEvents, Set generalEvents, Set modificationEvents) {
		this.typeRequest = typeRequest;
		this.user = user;
		this.date = date;
		this.eventTime = eventTime;
		this.office = office;
		this.description = description;
		this.channel = channel;
		this.priority = priority;
		this.level = level;
		this.state = state;
		this.maintenanceEvents = maintenanceEvents;
		this.transferEvents = transferEvents;
		this.sharedEvents = sharedEvents;
		this.generalEvents = generalEvents;
		this.modificationEvents = modificationEvents;
	}

	public Integer getIdRequest() {
		return this.idRequest;
	}

	public void setIdRequest(Integer idRequest) {
		this.idRequest = idRequest;
	}

	public TypeRequest getTypeRequest() {
		return this.typeRequest;
	}

	public void setTypeRequest(TypeRequest typeRequest) {
		this.typeRequest = typeRequest;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(String eventTime) {
		this.eventTime = eventTime;
	}

	public String getOffice() {
		return this.office;
	}

	public void setOffice(String office) {
		this.office = office;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Character getState() {
		return this.state;
	}

	public void setState(Character state) {
		this.state = state;
	}

	public Set getMaintenanceEvents() {
		return this.maintenanceEvents;
	}

	public void setMaintenanceEvents(Set maintenanceEvents) {
		this.maintenanceEvents = maintenanceEvents;
	}

	public Set getTransferEvents() {
		return this.transferEvents;
	}

	public void setTransferEvents(Set transferEvents) {
		this.transferEvents = transferEvents;
	}

	public Set getSharedEvents() {
		return this.sharedEvents;
	}

	public void setSharedEvents(Set sharedEvents) {
		this.sharedEvents = sharedEvents;
	}

	public Set getGeneralEvents() {
		return this.generalEvents;
	}

	public void setGeneralEvents(Set generalEvents) {
		this.generalEvents = generalEvents;
	}

	public Set getModificationEvents() {
		return this.modificationEvents;
	}

	public void setModificationEvents(Set modificationEvents) {
		this.modificationEvents = modificationEvents;
	}

}
