package co.edu.udea.usi.dto;
// Generated Apr 27, 2018 3:29:35 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * TransferEvent generated by hbm2java
 */
public class TransferEvent implements java.io.Serializable {

	private Integer idTEvent;
	private Request request;
	private Date date;
	private String stockNumber;
	private String originPlace;
	private String destinationPlace;
	private String user;
	private String observation;
	private String administrator;

	public TransferEvent() {
	}

	public TransferEvent(Request request) {
		this.request = request;
	}

	public TransferEvent(Request request, Date date, String stockNumber, String originPlace, String destinationPlace,
			String user, String observation, String administrator) {
		this.request = request;
		this.date = date;
		this.stockNumber = stockNumber;
		this.originPlace = originPlace;
		this.destinationPlace = destinationPlace;
		this.user = user;
		this.observation = observation;
		this.administrator = administrator;
	}

	public Integer getIdTEvent() {
		return this.idTEvent;
	}

	public void setIdTEvent(Integer idTEvent) {
		this.idTEvent = idTEvent;
	}

	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getStockNumber() {
		return this.stockNumber;
	}

	public void setStockNumber(String stockNumber) {
		this.stockNumber = stockNumber;
	}

	public String getOriginPlace() {
		return this.originPlace;
	}

	public void setOriginPlace(String originPlace) {
		this.originPlace = originPlace;
	}

	public String getDestinationPlace() {
		return this.destinationPlace;
	}

	public void setDestinationPlace(String destinationPlace) {
		this.destinationPlace = destinationPlace;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	public String getAdministrator() {
		return this.administrator;
	}

	public void setAdministrator(String administrator) {
		this.administrator = administrator;
	}

}
