package co.edu.udea.usi.dto;
// Generated Apr 27, 2018 3:29:35 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TypeRequest generated by hbm2java
 */
public class TypeRequest implements java.io.Serializable {

	private Integer idTypeRequest;
	private String name;
	private Set requests = new HashSet(0);

	public TypeRequest() {
	}

	public TypeRequest(Integer idTypeRequest, String name) {
		this.idTypeRequest = idTypeRequest;
		this.name = name;
	}

	public TypeRequest(String name, Set requests) {
		this.name = name;
		this.requests = requests;
	}

	public Integer getIdTypeRequest() {
		return this.idTypeRequest;
	}

	public void setIdTypeRequest(Integer idTypeRequest) {
		this.idTypeRequest = idTypeRequest;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

}
