package co.edu.udea.usi.dto;
// Generated Apr 27, 2018 3:29:35 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TypeUser generated by hbm2java
 */
public class TypeUser implements java.io.Serializable {

	private int idTypeUser;
	private String name;
	private Set users = new HashSet(0);

	public TypeUser() {
	}

	public TypeUser(int idTypeUser, String name) {
		this.idTypeUser = idTypeUser;
		this.name = name;
	}

	public TypeUser(int idTypeUser, String name, Set users) {
		this.idTypeUser = idTypeUser;
		this.name = name;
		this.users = users;
	}

	public int getIdTypeUser() {
		return this.idTypeUser;
	}

	public void setIdTypeUser(int idTypeUser) {
		this.idTypeUser = idTypeUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
