package co.edu.udea.usi.dto;
// Generated Apr 27, 2018 3:29:35 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String email;
	private MainFrame mainFrame;
	private TypeUser typeUser;
	private String name;
	private String office;
	private String phoneNumber;
	private String password;
	private Set requests = new HashSet(0);

	public User() {
	}

	public User(String email, TypeUser typeUser, String name) {
		this.email = email;
		this.typeUser = typeUser;
		this.name = name;
	}

	public User(String email, MainFrame mainFrame, TypeUser typeUser, String name, String office, String phoneNumber,
			String password, Set requests) {
		this.email = email;
		this.mainFrame = mainFrame;
		this.typeUser = typeUser;
		this.name = name;
		this.office = office;
		this.phoneNumber = phoneNumber;
		this.password = password;
		this.requests = requests;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public MainFrame getMainFrame() {
		return this.mainFrame;
	}

	public void setMainFrame(MainFrame mainFrame) {
		this.mainFrame = mainFrame;
	}

	public TypeUser getTypeUser() {
		return this.typeUser;
	}

	public void setTypeUser(TypeUser typeUser) {
		this.typeUser = typeUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOffice() {
		return this.office;
	}

	public void setOffice(String office) {
		this.office = office;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

}
